server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviedbfinal?createDatabaseIfNotExist=true
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      file-size-threshold: 2KB
      max-request-size: 215MB