server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/theatredbfinal?createDatabaseIfNotExist=true
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

